### Development environment configuration
[development.network]
rpc-url = "https://soroban-testnet.stellar.org"
network-passphrase = "Test SDF Network ; September 2015"
run-locally = false  # NO usar Docker local


[[development.accounts]]
name = "hornero" # Required. Keys for this account will be saved to `./.stellar/identity`
default = true # Optional. Whether to use this account as the `--source` for commands that need one.

[development.contracts]
fungible_allowlist_example = { client = true, constructor_args = "--admin hornero --manager hornero --initial_supply 1000000000000000000000000" }
nft_enumerable_example = { client = true, constructor_args = "--owner hornero" }

hornero = { client = true, constructor_args = "--admin hornero" }

# Rather than in one list, TOML allows specifying contracts in their own "sections"

# During initialization, these contracts will also be "spooned" into the development network,
# meaning that their data will match the live network at the given sequence number.
# [development.contracts.eurc]
# environment = "production"
# address = "C..."
# at-ledger-sequence = 50153603

### Staging environment configuration
[staging.network]
rpc-url = "https://soroban-testnet.stellar.org"
network-passphrase = "Test SDF Network ; September 2015"

[[staging.accounts]]
name = "testnet-user"
default = true

[staging.contracts]
# soroban-atomic-swap-contract = { id = "C123..." }
# soroban-auth-contract = { id = "C234..." }
# soroban-errors-contract = { id = "C345..." }
# soroban-hello-world-contract = { id = "C456..." }
# soroban-increment-contract = { id = "C567..." }
# soroban-token-contract = { id = "C678..." }
# eurc = { id = "C789..." }

### Production environment configuration
[production.network]
rpc-url = "https://our-custom-rpc-provider.cool"
network-passphrase = "Public Global Stellar Network ; September 2015"

[[production.accounts]]
name = "official-team-account"
default = true

[production.contracts]
# soroban-atomic-swap-contract = { id = "C987..." }
# soroban-auth-contract = { id = "C876..." }
# soroban-errors-contract = { id = "C765..." }
# soroban-hello-world-contract = { id = "C654..." }
# soroban-increment-contract = { id = "C543..." }
# soroban-token-contract = { id = "C432..." }
# eurc = { id = "C321..." }
